apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: z2eu7v3v0-nodejs 
  janus-idp.io/tekton: z2eu7v3v0-nodejs
  backstage.io/kubernetes-id: z2eu7v3v0-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: z2eu7v3v0-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml